[connections.snowflake]
account = "CLJQPFV-RZB54658"
user = "pchilamakuri"
password = "nnnp0r@a1t5SSS"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
